### ISSUE TITLE
Code too clean?

### ISSUE THREAD

**Issue by kivikakk** [bovarysme/fudge#1]
As far as I understand, systems code is meant to be obtuse, difficult to parse, full of magic numbers, undocumented behaviour and gotchas, and in general should not be maintainable.

I'm finding this all incredibly easy to read and understand. Possible bug?

**Comment by bovarysme** [comment]
Indeed, the current version of `fudge` is only a prototype and does not reflect the usual qualities of system code. Once all the planned features are implemented, `fudge` will be entirely rewritten in an esoteric language using "write once, read never" guidelines.

Thank you for bringing this to my attention!

**Comment by kivikakk** [comment]
Thanks for your response! A possible interim solution would be to use a minifier such as [pyminifier](https://liftoff.github.io/pyminifier/) to bring the codebase up to scratch. Alternatively, you could commit the `.pyc/`.pyo` object code, which has all the above desirable properties. You could even go one step further and then commit changes only to the object code while leaving the out-of-date `.py` source next to it.

At any rate, I'm satisfied that this problem will be fixed in due course, so I'll close the issue. Thanks for your attention!
