### ISSUE TITLE
The doctype is missing

### ISSUE THREAD

**Issue by ghost** [bovarysme/fudge#1]
Hello, I am a big fan of your project.

I noticed however that the doctype is missing in the served pages.
Do you have any idea on how to fix it?

I think that maybe the problem is here: https://github.com/bovarysme/fudge/blob/01c90f6243dd65289210abe24536421223ebd711/template/_layout.html#L1-L3

Thank you in advance.

**Comment by bovarysme** [comment]
Dear sir,

Thank you so much for bringing this issue to my attention, and pinpointing exactly where the solution needs to be implemented. I will immediately correct this unacceptable mistake. 

With regards to the discussion we had during that systems programming seminar, I have the regret to inform you that my HTML pages will *never* be minified. I strongly believe that newlines have free will, and should be able to roam the Web as they please. I hope you will understand the reasoning behind this decision.

I wish you luck on your quest to understand the borrow checker.

Kind regards.
