### ISSUE TITLE
Responsiveness code section broken in Safari

### ISSUE THREAD

**Issue by coltonhurst** [bovarysme/fudge#2]
Thank you for this awesome project. I really appreciate it!
Just noticed this when on Safari for mobile (iPhone) or when on Safari on the mac... When viewing code, the code breaks out of it's section when the screen size gets too small.

For example, navigate to: [https://bovarys.me/fudge/blob/template/blob.html](https://bovarys.me/fudge/blob/template/blob.html) using Safari on OS X (or Safari on an iPhone).

You will see the code overflows horizontally:

![safari-bug](https://user-images.githubusercontent.com/5691612/70562771-0babbe00-1b5b-11ea-87a5-1e2941b513b8.png)

**Comment by bovarysme** [comment]
Hi,

I'm glad you appreciate fudge!

The CSS generated by [Chroma](https://github.com/alecthomas/chroma) applies `overflow: auto` to the `table` element, which seems to behave differently in Safari. A quick-fix would be to apply it to the parent `div` instead, though I'm not sure it's the best solution. I'll have access to an iOS device in a week or so to perform more tests.

Thanks for your bug report!

**Comment by bovarysme** [comment]
It turns out Safari was freaking out because of a missing DOCTYPE. This was fixed in 12beb7d1ac037ea6df2689b3adb1b4040dae79d4.

Thanks again for your report!

**Comment by coltonhurst** [comment]
Wow- well, glad it was simple. No problem, thank you!
